- module-name: maa
  dlls:
    - from_filenames: 
        relative_path: 'bin'
        prefixes:
          - '*'
    - from_filenames: 
        relative_path: 'bin/plugins'
        prefixes:
          - '*'